config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  get 'pdf/index'
  post 'pdf/create'
  patch 'pdf/create'
  get 'pdf/delete'
  devise_scope :user do
    # get 'users/profil/:id', to: 'users/registrations#profil', as: 'profil'
    get 'users/registrations' => 'users/registrations#index'
    get 'users/registrations/new_user' => 'users/registrations#new_user'
    post 'users/registrations/create_user' => 'users/registrations#create_user'
    get 'users/registrations/active_user' => 'users/registrations#active_user'
    get 'users/registrations/desactive_user' => 'users/registrations#desactive_user'
    get 'users/registrations/reset_password' => 'users/registrations#reset_password'
  end


  resources :settings
  resources :exams
  resources :companies
  resources :trucks
  resources :doctors
  resources :staffs
  resources :drivers
  resources :vans
  resources :cars
  # resources :employees
  resources :events do
    collection do
      get 'add_mobile_unit'
      get 'remove_mobile_unit'
      get 'add_employee'
      get 'remove_employee'
      get 'add_exam'
      get 'remove_exam'
      get 'is_item_used'
      get 'send_confirmation_email'
    end
  end

  get '/visitors/load_data' => 'visitors#load_data'

  root 'visitors#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/staff.rb
class Staff < Employee
end

app/controllers/staffs_controller.rb
class StaffsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
  before_action :set_staff, only: [:show, :edit, :update, :destroy]
  before_action :set_breadcrumb

  # GET /staffs
  # GET /staffs.json
  def index
    @staffs = Staff.order_by_name
  end

  # GET /staffs/1
  # GET /staffs/1.json
  def show
  end

  # GET /staffs/new
  def new
    @staff = Staff.new
  end

  # GET /staffs/1/edit
  def edit
  end

  # POST /staffs
  # POST /staffs.json
  def create
    @staff = Staff.new(staff_params)

    respond_to do |format|
      if @staff.save
        format.html { redirect_to @staff, notice: 'Staff was successfully created.' }
        format.json { render :show, status: :created, location: @staff }
      else
        format.html { render :new }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /staffs/1
  # PATCH/PUT /staffs/1.json
  def update
    respond_to do |format|
      if @staff.update(staff_params)
        format.html { redirect_to @staff, notice: 'Staff was successfully updated.' }
        format.json { render :show, status: :ok, location: @staff }
      else
        format.html { render :edit }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /staffs/1
  # DELETE /staffs/1.json
  def destroy
    @staff.destroy
    respond_to do |format|
      format.html { redirect_to staffs_url, notice: 'Staff was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def set_breadcrumb
    @breadcrumb << ["Empleados", request.fullpath]
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_staff
      @staff = Staff.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def staff_params
      params.require(:staff).permit(:ci, :name, :lastname, :email, :phone1, :phone2, :degree, :workstation, :department, :available)
    end
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/views/staffs/_form.html.erb
<%= simple_form_for @staff, html: {role: "form"} do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <div class="row">
      <div class="col-md-4">
        <%= f.input :ci %>
      </div>
      <div class="col-md-4">
        <%= f.input :name %>
      </div>
      <div class="col-md-4">
        <%= f.input :lastname %>
      </div>
    </div>

    <div class="row">
      <div class="col-md-4">
        <%= f.input :email %>
      </div>
      <div class="col-md-4">
        <%= f.input :phone1 %>
      </div>
      <div class="col-md-4">
        <%= f.input :phone2 %>
      </div>
    </div>

    <div class="row">
      <div class="col-md-4">
        <%= f.input :degree, as: :select, collection: DEGREES, :prompt => 'Selecione opción' %> 
      </div>
      <div class="col-md-4">
        <%= f.input :workstation, as: :select, collection: WORKSTATIONS, :prompt => 'Selecione opción' %> 
      </div>
      <div class="col-md-4">
        <%= f.input :department, as: :select, collection: DEPARTMENTS, :prompt => 'Selecione opción' %> 
      </div>
    </div>
    
    <%= f.input :available %>
    
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-success" %>
    <%= link_to 'Cancelar', staffs_path, class: "btn btn-default" %>
  </div>
<% end %>

app/views/staffs/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Editar Empleado</h3>
  </div>
  <div class="panel-body">
    <%= render 'form', staff: @staff %>
  </div>
</div>

app/views/staffs/index.html.erb
<p id="notice"><%= notice %></p>
<div class="panel panel-default">
  <!-- Default panel contents -->
<div class="panel-heading">Todos los empleados</div>
  <div class="table-responsive">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Céluda</th>
          <th>Nombre Completo</th>
          <th>Correo</th>
          <!-- <th>Teléfono</th> -->
          <th>Celular</th>
          <!-- <th>Titulo</th> -->
          <!-- <th>Puesto T.</th> -->
          <th>Departamento</th>
          <th>Disponible</th>
          <th style="min-width: 98px">Acciones</th>
        </tr>
      </thead>

      <tbody>
        <% @staffs.each do |staff| %>
          <tr>
            <td><%= staff.ci %></td>
            <td><%= staff.full_last_name %></td>
            <td><%= staff.email.present? ? staff.email : "N/A" %></td>
            <!-- <td><%= staff.phone1 %></td> -->
            <td><%= staff.phone2.present? ? staff.phone2 : "N/A" %></td>
            <!-- <td><%= staff.degree %></td> -->
            <!-- <td><%= staff.workstation %></td> -->
            <td><%= staff.department.present? ? staff.department.capitalize : "N/A" %></td>
            <td><%= staff.available_to_s %></td>
            <td><%= link_to_show staff %>
            <%= link_to_edit staff, edit_staff_path(staff) %>
            <%= link_to_delete staff %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>


<br>

<%= link_to 'Nuevo Empleado', new_staff_path, class: "btn btn-default" %>

app/views/staffs/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Nuevo Empleado</h3>
  </div>
  <div class="panel-body">
    <%= render 'form', staff: @staff %>
  </div>
</div>

app/views/staffs/show.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Datos Automóvil</h3>
  </div>
  <div class="panel-body">
    <p>
		  <strong><%= Staff.human_attribute_name("ci") %>:</strong>
		  <%= @staff.ci %>
		</p>

		<p>
		  <strong><%= Staff.human_attribute_name("name") %>:</strong>
		  <%= @staff.name %>
		</p>

		<p>
		  <strong><%= Staff.human_attribute_name("lastname") %>:</strong>
		  <%= @staff.lastname.capitalize if @staff.lastname %>
		</p>

		<p>
		  <strong><%= Staff.human_attribute_name("email") %>:</strong>
		  <%= @staff.email.capitalize if @staff.email%>
		</p>

		<p>
		  <strong><%= Staff.human_attribute_name("phone1") %>:</strong>
		  <%= @staff.phone1 %>
		</p>

		<p>
		  <strong><%= Staff.human_attribute_name("phone2") %>:</strong>
		  <%= @staff.phone2 %>
		</p>

		<p>
		  <strong><%= Staff.human_attribute_name("degree") %>:</strong>
		  <%= @staff.degree %>
		</p>

		<p>
		  <strong><%= Staff.human_attribute_name("workstation") %>:</strong>
		  <%= @staff.workstation %>
		</p>

		<p>
		  <strong><%= Staff.human_attribute_name("department") %>:</strong>
		  <%= @staff.department %>
		</p>

		<p>
		  <strong><%= Staff.human_attribute_name("available_to_s") %>:</strong>
		  <%= @staff.available_to_s %>
		</p>

  </div>
</div>


<div class="form-actions">
  <%= link_to 'Editar', edit_staff_path(@staff), class: "btn btn-success" %>
  <%= link_to 'Lista de Empleados', staffs_path, class: "btn btn-default" %>
</div>