config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  get 'pdf/index'
  post 'pdf/create'
  patch 'pdf/create'
  get 'pdf/delete'
  devise_scope :user do
    # get 'users/profil/:id', to: 'users/registrations#profil', as: 'profil'
    get 'users/registrations' => 'users/registrations#index'
    get 'users/registrations/new_user' => 'users/registrations#new_user'
    post 'users/registrations/create_user' => 'users/registrations#create_user'
    get 'users/registrations/active_user' => 'users/registrations#active_user'
    get 'users/registrations/desactive_user' => 'users/registrations#desactive_user'
    get 'users/registrations/reset_password' => 'users/registrations#reset_password'
  end


  resources :settings
  resources :exams
  resources :companies
  resources :trucks
  resources :doctors
  resources :staffs
  resources :drivers
  resources :vans
  resources :cars
  # resources :employees
  resources :events do
    collection do
      get 'add_mobile_unit'
      get 'remove_mobile_unit'
      get 'add_employee'
      get 'remove_employee'
      get 'add_exam'
      get 'remove_exam'
      get 'is_item_used'
      get 'send_confirmation_email'
    end
  end

  get '/visitors/load_data' => 'visitors#load_data'

  root 'visitors#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
    before_action :authenticate_user!
	before_action :get_data, only: [:index]
  def index
    beginning_of_week = Date.today.beginning_of_week
    end_of_week = beginning_of_week.end_of_week
    @weekly_events = Event.where(start: beginning_of_week..end_of_week).or(Event.where(end: beginning_of_week..end_of_week))
    beginning_of_day = Date.today.beginning_of_day
    end_of_day = beginning_of_day.end_of_day
    # @daily_events = Event.where(start: beginning_of_day..end_of_day).or(Event.where(end: beginning_of_day..end_of_day))
    @daily_events = Event.where("events.start <= ? AND ? <= events.end",  Date.today,  Date.today)
  end

  def load_data
  	require 'csv'
    # Clear database
    Rails.application.eager_load!
    ActiveRecord::Base.descendants.each { |c| c.delete_all unless c.to_s == "ActiveRecord::SchemaMigration" || c.to_s == "ApplicationRecord"}
    # ActiveRecord::Base.connection.reset_pk_sequence!("users")
    ActiveRecord::Base.connection.reset_pk_sequence!("exams")
    ActiveRecord::Base.connection.reset_pk_sequence!("companies")
    ActiveRecord::Base.connection.reset_pk_sequence!("employees")
    ActiveRecord::Base.connection.reset_pk_sequence!("event_employees")
    ActiveRecord::Base.connection.reset_pk_sequence!("event_mobile_units")
    ActiveRecord::Base.connection.reset_pk_sequence!("events")
    ActiveRecord::Base.connection.reset_pk_sequence!("mobile_units")
    ActiveRecord::Base.connection.reset_pk_sequence!("pdfs")
  	# Add Companies
    datafile = Rails.root + 'db/empresas.csv'
    CSV.foreach(datafile, headers: true) do |row|
      company = Company.where(:name => row[0]).last
      unless company.present?
        c = Company.new
        c.name = row[0]
        c.ruc = row[1]
        c.direcction = row[2]
        c.sector = row[3]
        c.contact_name = row[4]
        c.contact_email = row[5]
        c.doctor_name = row[6]
        c.doctor_email = row[7]
        c.billing_name = row[8]
        c.billing_email = row[9]
        # c.user_id = row[10]
        c.save
      end
    end
    # Add examenes
    datafile = Rails.root + 'db/examenes2.csv'
    CSV.foreach(datafile, headers: true, ) do |row|
      exam = Exam.where(:code => row[0]).last
      unless exam.present?
        e = Exam.new
        e.code = row[0].to_s
        e.name = row[1].to_s
        e.activated = true
        e.province_value = 0
        e.m_units_value = 0
        e.city_value = 0
        Rails.logger.info "==>> e : #{e.inspect}"
        Rails.logger.info "==>> e.save : #{e.save}"
        Rails.logger.info "==>> e.errors : #{e.errors.full_messages.join(", ")}"

      end
    end
    call_rake("tasks:datos_iniciales")
    redirect_to root_path, alert: "Base de datos cargada"
  end
end

app/helpers/visitors_helper.rb
module VisitorsHelper
end

app/views/visitors/_table_drivers.html.erb
<div class="today-events">
	<div class="panel panel-default">
  <!-- Default panel contents -->
	  <div class="panel-heading">
	  	<span style="margin-right: 5px" class='glyphicon glyphicon-time' aria-hidden='true'></span> 
	  	
	  	<%= title %>
	  </div>
	  <div class="table-container">
	  	<table class="table panel-events" style="font-size: 12px">
				<thead>
				
					<tr>
						<th>
							Nombre
						</th>
						<th>
							Telefono
						</th>
						<th>
							Tipo Vehículo
						</th>
						<th>
							Placa
						</th>
						<th>
							Programas
						</th>
						
					</tr>
				</thead>				    
				<tbody>
					<% if cars.any? %>
				  	<%- cars.last(10).each do |car| %>
				  		<tr>
								<td>
									<%= "#{car.driver ? car.driver.full_name : "N/A"}"%>
								</td>
								<td>
									<%= "#{car.driver ? car.driver.phone1 : "N/A"}"%>
								</td>
								<td>
									<%= "#{car.model_name.human}"%>
								</td>
								<td>
									<%= "#{car.plate}"%>
								</td>
								<td>
									<%- if car.current_event_items.any? %>
										<%- car.current_event_items.each do |event_item|%>
											<%- if event_item.event.present? %>
												<%= event_item.event.present? ? link_to(event_item.event.full_name, event_path(event_item.event)) : "N/A" %>	
												<br/>
											<%- end %>
										<% end %>
									<% else %>
										<strong>Disponible</strong>
									<% end %>
								</td>
								
							</tr>
				  	<%- end %>
				  <% else %>
				 	 	<tr>
							<td colspan="4">
								No registra eventos
							</td>
						</tr>
				  <% end %>

					
				</tbody>
		  </table>
	  	
	  </div>
	  

	</div>
</div>

app/views/visitors/_table_events.html.erb
<div class="today-events">
	<div class="panel panel-default">
  <!-- Default panel contents -->
	  <div class="panel-heading">
	  	<span style="margin-right: 5px" class='glyphicon glyphicon-time' aria-hidden='true'></span> 
	  	
	  	<%= title %>
	  </div>
	  <div class="table-container">
	  	<table class="table reposive panel-events" style="font-size: 12px">
				<thead>
								    
					<tr>
						<th>
							Titulo
						</th>
						<th>
							Responsble
						</th>
						<th>
							F. Inicio
						</th>
						<th>
							F. Fin
						</th>

						<th>
							Estado
						</th>
						
					</tr>
				</thead>
				<tbody>
					<% if events.any? %>
				  	<%- events.last(10).each do |event| %>
				  		<%- date_format = '%Y-%m-%d' %>
				  		<tr>
								<td>
									<%= "#{event.full_name}"%>
								</td>
								<td>
									<%= "#{event.owner}"%>
								</td>
								<td>
									<%= "#{event.start.strftime(date_format)}"%>
								</td>
								<td>
									<%= "#{event.end.strftime(date_format)}"%>
								</td>
								<td>
									<%= "#{select_name(EVENT_STATUS, event.status)}"%>
								</td>
								
							</tr>
				  	<%- end %>
				  <% else %>
				 	 	<tr>
							<td colspan="4">
								No registra eventos
							</td>
						</tr>
				  <% end %>

					
				</tbody>
		  </table>
	  	
	  </div>
	  

	</div>
</div>

app/views/visitors/_table_menu.html.erb
<div class="top-menus">
	<ul class="list-group">
		<li class="list-group-item">
			<% if current_user.avatar.present?  %>
				<img src="<%= current_user.avatar.url %>">
			<% else %>
				<img src="/images/user.png">
			<% end %>
			
		</li>
		
	  <li class="list-group-item">
	  	<%= link_to 'Mi cuenta', edit_user_registration_path %>
	  </li>
	  <li class="list-group-item">
	  	<%= link_to "Mis programas <span class='badge'>#{@my_events}</span>".html_safe, events_path %>
	  </li>
	  
	  <li class="list-group-item">
	  	<%= link_to "Cerrar sesión", destroy_user_session_path, method: :delete %>
	  </li>
	  <!-- <a href="/visitors/load_data" data-confirm="Esta seguro?" style="width: 100%" class="btn btn-primary" role="button">
	  	<span style="margin-right: 5px" class='glyphicon glyphicon-cog' aria-hidden='true'></span>
	  	Cargar Datos
	  </a> 	  -->
	</ul>
	<% if current_user.role?(:admin) %>
		<a href="<%= settings_path%>" style="width: 100%" class="btn btn-primary" role="button">
	  	<span style="margin-right: 5px" class='glyphicon glyphicon-cog' aria-hidden='true'></span>
	  	Configuración
	  </a> 
	<% end %>
</div>

app/views/visitors/index.html.erb
<div class="row">
	<div class="col-md-12">
		<div class="calendar empty">
		</div>
		<div class="lds-spinner"><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div></div>
	</div>
</div>
<br/>
<br/>
<div class="row">
	<div class="col-md-12">
		<div class="resources">
			<%= render "table_events", title: "Programas de la semana", events: @weekly_events %>
			<%= render "table_events", title: "Programas de hoy", events: @daily_events %>
			<%= render "table_drivers", title: "Conductores por programa", cars: @all_cars %>
		</div>
	</div>
</div>