config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  get 'pdf/index'
  post 'pdf/create'
  patch 'pdf/create'
  get 'pdf/delete'
  devise_scope :user do
    # get 'users/profil/:id', to: 'users/registrations#profil', as: 'profil'
    get 'users/registrations' => 'users/registrations#index'
    get 'users/registrations/new_user' => 'users/registrations#new_user'
    post 'users/registrations/create_user' => 'users/registrations#create_user'
    get 'users/registrations/active_user' => 'users/registrations#active_user'
    get 'users/registrations/desactive_user' => 'users/registrations#desactive_user'
    get 'users/registrations/reset_password' => 'users/registrations#reset_password'
  end


  resources :settings
  resources :exams
  resources :companies
  resources :trucks
  resources :doctors
  resources :staffs
  resources :drivers
  resources :vans
  resources :cars
  # resources :employees
  resources :events do
    collection do
      get 'add_mobile_unit'
      get 'remove_mobile_unit'
      get 'add_employee'
      get 'remove_employee'
      get 'add_exam'
      get 'remove_exam'
      get 'is_item_used'
      get 'send_confirmation_email'
    end
  end

  get '/visitors/load_data' => 'visitors#load_data'

  root 'visitors#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/setting.rb
class Setting < ApplicationRecord
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_setting, only: [:show, :edit, :update, :destroy]
  before_action :set_breadcrumb

  # GET /settings
  # GET /settings.json
  def index
    @settings = Setting.all
  end

  # GET /settings/1
  # GET /settings/1.json
  def show
  end

  # GET /settings/new
  def new
    @setting = Setting.new
  end

  # GET /settings/1/edit
  def edit
  end

  # POST /settings
  # POST /settings.json
  def create
    @setting = Setting.new(setting_params)

    respond_to do |format|
      if @setting.save
        format.html { redirect_to @setting, notice: 'Setting was successfully created.' }
        format.json { render :show, status: :created, location: @setting }
      else
        format.html { render :new }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /settings/1
  # PATCH/PUT /settings/1.json
  def update
    respond_to do |format|
      if @setting.update(setting_params)
        format.html { redirect_to @setting, notice: 'Setting was successfully updated.' }
        format.json { render :show, status: :ok, location: @setting }
      else
        format.html { render :edit }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /settings/1
  # DELETE /settings/1.json
  def destroy
    @setting.destroy
    respond_to do |format|
      format.html { redirect_to settings_url, notice: 'Setting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def set_breadcrumb
    @breadcrumb << ["Configuración", request.fullpath]
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_setting
      @setting = Setting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def setting_params
      params.require(:setting).permit(:event_notification_email)
    end
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/settings/_form.html.erb
<%= simple_form_for(@setting) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :event_notification_email %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/settings/edit.html.erb
<h1>Editing Setting</h1>

<%= render 'form', setting: @setting %>

<%= link_to 'Show', @setting %> |
<%= link_to 'Back', settings_path %>

app/views/settings/index.html.erb
<p id="notice"><%= notice %></p>
<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">Todos las Configuraciones</div>
  <div class="table-responsive">
    <table class="table table-hover">
      <thead>
        <thead>
          <tr>
            <th>Nombre</th>
            <th>Valor</th>
            <th ></th>
          </tr>
        </thead>
      </thead>
      <tbody>
        <% @settings.each do |setting| %>
          <tr>
            <td><%= setting.name %></td>
            <td><%= setting.value %></td>
            <td>
              <%= link_to 'Ver', setting, class: "btn btn-default btn-xs"  %>
              <%= link_to 'Editar', edit_setting_path(setting), class: "btn btn-default btn-xs"  %>
              <%= link_to 'Eliminar', setting, method: :delete, data: { confirm: 'Esta seguro?' }, class: "btn btn-default btn-xs"  %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<br>
<%= link_to 'Nueva configuración', new_setting_path, class: "btn btn-default" %>

app/views/settings/new.html.erb
<h1>New Setting</h1>

<%= render 'form', setting: @setting %>

<%= link_to 'Back', settings_path %>

app/views/settings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Event notification email:</strong>
  <%= @setting.event_notification_email %>
</p>

<%= link_to 'Edit', edit_setting_path(@setting) %> |
<%= link_to 'Back', settings_path %>