config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  get 'pdf/index'
  post 'pdf/create'
  patch 'pdf/create'
  get 'pdf/delete'
  devise_scope :user do
    # get 'users/profil/:id', to: 'users/registrations#profil', as: 'profil'
    get 'users/registrations' => 'users/registrations#index'
    get 'users/registrations/new_user' => 'users/registrations#new_user'
    post 'users/registrations/create_user' => 'users/registrations#create_user'
    get 'users/registrations/active_user' => 'users/registrations#active_user'
    get 'users/registrations/desactive_user' => 'users/registrations#desactive_user'
    get 'users/registrations/reset_password' => 'users/registrations#reset_password'
  end


  resources :settings
  resources :exams
  resources :companies
  resources :trucks
  resources :doctors
  resources :staffs
  resources :drivers
  resources :vans
  resources :cars
  # resources :employees
  resources :events do
    collection do
      get 'add_mobile_unit'
      get 'remove_mobile_unit'
      get 'add_employee'
      get 'remove_employee'
      get 'add_exam'
      get 'remove_exam'
      get 'is_item_used'
      get 'send_confirmation_email'
    end
  end

  get '/visitors/load_data' => 'visitors#load_data'

  root 'visitors#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/company.rb
class Company < ApplicationRecord
	validates :ruc, :name, presence: true
	scope :order_by_name, -> {order(:name)}

	def full_contact_name
		if self.contact_email.present? && self.contact_name.present?
			"#{self.contact_name} (#{self.contact_email})"
		elsif self.contact_name.present?
			self.contact_name
		else
			"No asignado"
		end
	end

	def full_doctor_name
		if self.doctor_email.present? && self.doctor_name.present?
			"#{self.doctor_name} (#{self.doctor_email})"
		elsif self.doctor_name.present?
			self.doctor_name
		else
			"No asignado"
		end
	end

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
  before_action :set_company, only: [:show, :edit, :update, :destroy]
  before_action :set_breadcrumb
  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.order_by_name.page(params[:page]).per(15)
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def set_breadcrumb
    @breadcrumb << ["Empresas", request.fullpath]
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :ruc, :direcction, :sector, :contact_name, :contact_email, :doctor_name, :doctor_email, :billing_name, :billing_email, :description, :text)
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= simple_form_for @company, html: {role: "form"} do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <div class="row">
      <!-- Company -->
      <div class="col-md-6">
        <div class="row">
          <div class="col-md-12">
            <%= f.input :ruc %>
          </div>
          <div class="col-md-12">
            <%= f.input :name %>
          </div>
          <div class="col-md-12">
            <%= f.input :sector, as: :select, collection: SECTOR_COMPANY, :prompt => 'Selecione opción' %> 
          </div>
          <div class="col-md-12">
            <%= f.input :direcction, as: :text %>
          </div>
          <div class="col-md-12">
            <%= f.input :description, as: :text %>
          </div>
        </div>
      </div>
      <!-- Contact Informacion -->
      <div class="col-md-6">
        <div class="row">
          <div class="col-md-12">
            <%= f.input :contact_name %>
          </div>
          <div class="col-md-12">
            <%= f.input :contact_email %>
          </div>
          <div class="col-md-12">
            <%= f.input :doctor_name %>
          </div>
          <div class="col-md-12">
            <%= f.input :doctor_email %>
          </div>
         <!--  <div class="col-md-12">
            <%= f.input :billing_name %>
          </div>
          <div class="col-md-12">
            <%= f.input :billing_email %>
          </div> -->
        </div>
      </div>
    </div>
</div>
<div class="form-actions">
  <%= f.button :submit, class: "btn btn-success" %>
  <%= link_to 'Cancelar', cars_path, class: "btn btn-default" %>
</div>
<% end %>

app/views/companies/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Editar Empresa</h3>
  </div>
  <div class="panel-body">
    <%= render 'form', company: @company %>
  </div>
</div>

app/views/companies/index.html.erb
<p id="notice"><%= notice %></p>
<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">Todos las Empresas</div>
  <div class="table-responsive">
    <table class="table table-hover">
      <thead>
        <thead>
          <tr>
            <th>Nombre</th>
            <th>RUC</th>
            <!-- <th>Dirección</th> -->
            <th>Sector</th>
            <th>Nombre Contacto</th>
            <th>Nombre Doctor</th>
            <th style="min-width: 98px">Acciones</th>
          </tr>
        </thead>
      </thead>
      <tbody>
        <% @companies.each do |company| %>
          <tr>
            <td><%= company.name %></td>
            <td><%= company.ruc %></td>
            <!-- <td><%= company.direcction %></td> -->
            <td><%= company.sector %></td>
            <td><%= company.full_contact_name %></td>
            <td><%= company.full_doctor_name %></td>
            <!-- <td><%= company.billing_name %></td>
            <td><%= company.billing_email %></td>
            <td><%= company.description %></td>
            <td><%= company.text %></td> -->
            <td>
              <%= link_to_show company %>
              <%= link_to_edit company, edit_company_path(company) %>
              <%= link_to_delete company %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div>
    <%= paginate @companies %>
  </div>
</div>
<br>
<%= link_to 'Nueva Empresa', new_company_path, class: "btn btn-default" %>

app/views/companies/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Nueva Empresa</h3>
  </div>
  <div class="panel-body">
    <%= render 'form', company: @company %>
  </div>
</div>

app/views/companies/show.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Datos Empresa</h3>
  </div>
  <div class="panel-body">
    <p>
      <strong><%= Company.human_attribute_name("name") %>:</strong>
      <%= @company.name %>
    </p>

    <p>
      <strong><%= Company.human_attribute_name("ruc") %>:</strong>
      <%= @company.ruc %>
    </p>

    <p>
      <strong><%= Company.human_attribute_name("direcction") %>:</strong>
      <%= @company.direcction if  @company.direcction %>
    </p>

    <p>
      <strong><%= Company.human_attribute_name("description") %>:</strong>
      <%= @company.description if  @company.description %>
    </p>

    <p>
      <strong><%= Company.human_attribute_name("contact_name") %>:</strong>
      <%= @company.contact_name if  @company.contact_name %>
    </p>

    <p>
      <strong><%= Company.human_attribute_name("contact_email") %>:</strong>
      <%= @company.contact_email if  @company.contact_email %>
    </p>

    <p>
      <strong><%= Company.human_attribute_name("doctor_name") %>:</strong>
      <%= @company.doctor_name if  @company.doctor_name %>
    </p>

    <p>
      <strong><%= Company.human_attribute_name("doctor_email") %>:</strong>
      <%= @company.doctor_email if  @company.doctor_email %>
    </p>

    <p>
      <strong><%= Company.human_attribute_name("billing_name") %>:</strong>
      <%= @company.billing_name if  @company.billing_name %>
    </p>

    <p>
      <strong><%= Company.human_attribute_name("billing_email") %>:</strong>
      <%= @company.billing_email if  @company.billing_email %>
    </p>

  </div>
</div>


<div class="form-actions">
  <%= link_to 'Editar', edit_company_path(@company), class: "btn btn-success" if can? :edit, @company %>
  <%= link_to 'Lista de empresas', companies_path, class: "btn btn-default" %>
</div>